private["_type","_ret","_var","_mode"];
_type = [_this,0,"",[""]] call BIS_fnc_param;
_mode = [_this,1,-1,[0]] call BIS_fnc_param;
if(_type == "" OR _mode == -1) exitWith {[]};
switch (_mode) do
{
	case 0:
	{
		switch (_type) do
		{
			case "driver": {_var = "license_civ_driver"};
			case "boat": {_var = "license_civ_boat"};
			case "pilot": {_var = "license_civ_air"};
			case "gun": {_var = "license_civ_gun"};
			case "dive": {_var = "license_civ_dive"};
			case "oil": {_var = "license_civ_oil"};
			case "cair": {_var = "license_cop_air"};
			case "swat": {_var = "license_cop_swat"};
			case "cg": {_var = "license_cop_cg"}; 
			case "heroin": {_var = "license_civ_heroin"}; 
			case "marijuana": {_var = "license_civ_marijuana"};
			case "medmarijuana": {_var = "license_civ_medmarijuana"};
			case "gang": {_var = "license_civ_gang"};
			case "rebel": {_var = "license_civ_rebel"};
			case "truck":{_var = "license_civ_truck"};
			case "diamond": {_var = "license_civ_diamond"};
			case "salt": {_var = "license_civ_salt"};
			case "cocaine": {_var = "license_civ_coke"};
			case "sand": {_var = "license_civ_sand"};
			case "iron": {_var = "license_civ_iron"};
			case "copper": {_var = "license_civ_copper"};
			case "cement": {_var = "license_civ_cement"};
			case "mair": {_var = "license_med_air"};
			case "home": {_var = "license_civ_home"};
		    case "uranium": {_var = "license_civ_uranium"}; 
			case "uranium1": {_var = "license_civ_uranium"};
			case "uranium2": {_var = "license_civ_uranium"};
			case "uranium2b": {_var = "license_civ_uranium"}; 
			case "uranium3": {_var = "license_civ_uranium"};
			case "uranium4": {_var = "license_civ_uranium"};
			case "skull": {_var = "license_civ_skull"};
			case "meth97": {_var = "license_civ_meth97"};
            case "copdriver": {_var = "license_cop_driver"};
            case "grapes": {_var = "license_civ_grapes"};			
			case "liquor": {_var = "license_civ_liquor"};
			case "beer": {_var = "license_civ_liquor"};
			case "stiller": {_var = "license_civ_stiller"};
			case "whiskey": {_var = "license_civ_stiller"};
			case "moonshine": {_var = "license_civ_stiller"};
			case "mash": {_var = "license_civ_stiller"};
			case "bottledshine": {_var = "license_civ_bottler"};
			case "bottledbeer": {_var = "license_civ_bottler"};
			case "bottledwhiskey": {_var = "license_civ_bottler"};
			case "bottler": {_var = "license_civ_bottler"};
			case "glassbottle": {_var = "license_civ_bottler"};	
			case "depanneur": {_var = "license_civ_depanneur"};
            case "taxi": {_var = "license_civ_taxi"}; 
            case "special": {_var = "license_civ_special"};
			case "merc": {_var = "license_civ_merc"};
			case "merc_reb": {_var = "license_civ_merc_reb"};			
			case "usine": {_var = "license_civ_usine"};		
			case "chauffeur": {_var = "license_civ_chauffeur"};			
            case "lingot": {_var = "license_civ_lingot"};	
			case "bountyh": {_var = "license_civ_bountyh"};
			case "cea": {_var = "license_cop_cea"};			
			case "gang1": {_var = "license_reb_gang1"};		
			case "gang2": {_var = "license_reb_gang2"};		
			case "gang3": {_var = "license_reb_gang3"};	
			case "gang4": {_var = "license_reb_gang4"};	
			case "gang5": {_var = "license_reb_gang5"};	
			case "gang6": {_var = "license_reb_gang6"};	
			case "gang7": {_var = "license_reb_gang7"};	
			case "gang8": {_var = "license_reb_gang8"};	
			case "gang9": {_var = "license_reb_gang9"};		
			case "gang10": {_var = "license_reb_gang10"};	
			case "mineralogiste": {_var = "license_civ_mineralogiste"};	
			case "platine": {_var = "license_civ_mineralogiste"};			
			default {_var = ""};
		};
	};
	
	case 1:
	{
		switch (_type) do
		{
			case "license_civ_driver": {_var = "driver"};
			case "license_civ_boat": {_var = "boat"};
			case "license_civ_air": {_var = "pilot"};
			case "license_civ_gun": {_var = "gun"};
			case "license_civ_dive": {_var = "dive"};
			case "license_civ_oil": {_var = "oil"};
			case "license_cop_air": {_var = "cair"};
			case "license_cop_swat": {_var = "swat"};
			case "license_cop_cg": {_var = "cg"};
			case "license_civ_heroin": {_var = "heroin"}; 
			case "license_civ_marijuana": {_var = "marijuana"};
			case "license_civ_medmarijuana": {_var = "medmarijuana"}; 
			case "license_civ_gang": {_var = "gang"}; 
			case "license_civ_rebel": {_var = "rebel"};
			case "license_civ_truck":{_var = "truck"};
			case "license_civ_diamond": {_var = "diamond"};
			case "license_civ_salt": {_var = "salt"};
			case "license_civ_coke": {_var = "cocaine"};
			case "license_civ_sand": {_var = "sand"};
			case "license_civ_iron": {_var = "iron"};
			case "license_civ_copper": {_var = "copper"};
			case "license_civ_cement": {_var = "cement"};
			case "license_med_air": {_var = "mair"};
			case "license_civ_home": {_var = "home"};
			case "license_civ_uranium": {_var = "uranium"};
			case "license_civ_archeologue": {_var = "archeologue"};
			case "license_civ_meth97": {_var = "meth97"};
			case "license_civ_glassArt": {_var = "glassArt"};
			case "license_civ_alcool": {_var = "alcool"};
            case "license_civ_depanneur": {_var = "depanneur"}; 
            case "license_civ_taxi": {_var = "taxi"}; 
            case "license_cop_driver": {_var = "copdriver"}; 
            case "license_civ_grapes": {_var = "grapes"};
            case "license_civ_moonshine": {_var = "moonshine"};
            case "license_civ_special": {_var = "special"};
            case "license_civ_merc": {_var = "merc"};
            case "license_civ_merc_reb": {_var = "merc_reb"};			
			case "license_civ_usine": {_var = "usine"};
			case "license_civ_bountyh": {_var = "bountyh"};
			case "license_civ_chauffeur": {_var = "chauffeur"};			
			case "license_civ_lingot": {_var = "lingot"};
			case "license_cop_cea": {_var = "cea"}; 
			case "license_reb_gang1": {_var = "gang1"}; 
			case "license_reb_gang2": {_var = "gang2"}; 
			case "license_reb_gang3": {_var = "gang3"}; 	
			case "license_reb_gang4": {_var = "gang4"}; 
			case "license_reb_gang5": {_var = "gang5"}; 	
			case "license_reb_gang6": {_var = "gang6"}; 
			case "license_reb_gang7": {_var = "gang7"}; 	
			case "license_reb_gang8": {_var = "gang8"}; 
			case "license_reb_gang9": {_var = "gang9"}; 	
			case "license_reb_gang10": {_var = "gang10"}; 
			case "license_civ_mineralogiste": {_var = "platine"};			
			default {_var = ""};
		};
	};
};
_ret = [_var,(if(_var != "") then {([_var] call life_fnc_varToStr)})];
_ret;