_this enableSimulation false;
_this allowDamage false;
_this setObjectTexture [0, "images\panneaux\equipement.paa"];
_this addAction["<t color='#ADFF2F'>DAB</t>",life_fnc_atmMenu];
_this addAction["Marché Mercenaire",life_fnc_virt_menu,"marketmerc",0,false,false,"",' license_civ_merc && playerSide == civilian'];
_this addAction["Vêtements Mercenaire",life_fnc_clothingMenu,"merc",0,false,false,"",' license_civ_merc && playerSide == civilian'];
_this addAction["Armes Mercenaire",life_fnc_weaponShopMenu,"merc",0,false,false,"",' license_civ_merc && playerSide == civilian'];
_this addAction["Concessionnaire",life_fnc_vehicleShopMenu,["merc",civilian,["veh_merc"],"civ","Vehicule Mercenaire"]];
_this addAction["Garage",  {   [[getPlayerUID player,playerSide,"Car",player],"TON_fnc_getVehicles",false,false] spawn life_fnc_MP; life_garage_type = "Car";  createDialog "Life_impound_menu";   disableSerialization;   ctrlSetText[2802,"Recherche..."];   life_garage_sp = "veh_merc";  }];
_this addAction["Garage Hélico",  {   [[getPlayerUID player,playerSide,"Air",player],"TON_fnc_getVehicles",false,false] spawn life_fnc_MP;  life_garage_type = "Air"; createDialog "Life_impound_menu";   disableSerialization;   ctrlSetText[2802,"Recherche..."];   life_garage_sp = "veh_merc";  }];
_this addAction["Mettre au garage",  {   private["_nearVehicle"];   _nearVehicle = nearestObjects[(getPos (_this select 0)),["Car","Ship","Air"],35] select 0;   if(isNil "_nearVehicle") exitWith {hint "Gare ton véhicule a coté !";};   [[_nearVehicle,false,(_this select 1)],"TON_fnc_vehicleStore",false,false] spawn life_fnc_MP;   hint "Mise au garage..."; life_garage_store = true;  },"",0,false,false,"",'!life_garage_store'];