private["_var"];
_var = [_this,0,"",[""]] call BIS_fnc_param;
if(_var == "") exitWith {""};
switch (_var) do
{
case "life_inv_oilu": {"Pétrole brut"};
case "life_inv_oilp": {"Pétrole raffiné"};
case "life_inv_heroinu": {"Pavot"};
case "life_inv_heroinp": {"Héroïne"};
case "life_inv_cannabis": {"Cannabis"};
case "life_inv_marijuana": {"Herbe"};
case "life_inv_apple": {"Kg de pommes"};
case "life_inv_rabbit": {"Viande de lapin"};
case "life_inv_salema": {"Filet de saumon"};
case "life_inv_ornate": {"Filet de dorade"};
case "life_inv_mackerel": {"Filet de maquereau"};
case "life_inv_tuna": {"Filet de thon rouge"};
case "life_inv_mullet": {"Viande de mulet"};
case "life_inv_catshark": {"Filet de poisson chat"};
case "life_inv_turtle": {"Viande de tortue"};
case "life_inv_fishingpoles": {"Canne à peche"};
case "life_inv_water": {"Bouteille d'eau"};
case "life_inv_coffee": {"Expresso"};
case "life_inv_turtlesoup": {"Soupe de Tortue"};
case "life_inv_donuts": {"Donut"};
case "life_inv_fuelE": {"Jerican vide"};
case "life_inv_fuelF": {"Jerican plein"};
case "life_inv_pickaxe": {"Pioche"};
case "life_inv_copperore": {"Minerai de cuivre"};
case "life_inv_ironore": {"Minerai de fer"};
case "life_inv_ironr": {"Lingot de fer"};
case "life_inv_copperr": {"Lingot de cuivre"};
case "life_inv_sand": {"Sable"};
case "life_inv_salt": {"Sel"};
case "life_inv_saltr": {"Sel raffiné"};
case "life_inv_glass": {"Verre"};
case "life_inv_diamond": {"Diamant brut"};
case "life_inv_diamondr": {"Diamant taillé"};
case "life_inv_tbacon": {"Bacon"};
case "life_inv_redgull": {"RedBull"};
case "life_inv_lockpick": {"Outil de crochetage"};
case "life_inv_peach": {"Kg de pêches"};
case "life_inv_coke": {"Feuille de coca"};
case "life_inv_cokep": {"Cocaine"};
case "life_inv_puranium": {"Produit Uranium"};
case "life_inv_uranium1": {"Dechets Uranium"};
case "life_inv_uranium2": {"Uranium Brut"};
case "life_inv_uranium3": {"Uranium Purifié"};
case "life_inv_uranium4": {"Uranium Concentré"};
case "life_inv_uranium": {"Uranium"};
case "life_inv_skull": {"Crâne"};
case "life_inv_skullp": {"Antiquité restaurée"};
case "life_inv_spikeStrip": {"Herse"};
case "life_inv_rock": {"Pierre"};
case "life_inv_cement": {"Sac de ciment"};
case "life_inv_goldbar": {"Lingot d'or"};
case "life_inv_ephedrine": {"Fiole d'ephedrine"};
case "life_inv_phosphore": {"Sac de phosphore"};
case "life_inv_metylamine": {"Bidon de metylamine"};
case "life_inv_iode": {"Fiole d'iode"};
case "life_inv_meth97": {"Meth 97"};
case "life_inv_mash": {"Mash"};
case "life_inv_yeast": {"Levure"};
case "life_inv_rye": {"Céréales"};
case "life_inv_hops": {"Houblon"};
case "life_inv_whiskey": {"Whisky distillé"};
case "life_inv_beerp": {"Biere fermantée"};
case "life_inv_bottles": {"Bouteille vide"};
case "life_inv_cornmeal": {"Grains de mais"};
case "life_inv_bottledwhiskey": {"Bouteille de Whisky"};
case "life_inv_bottledbeer": {"Bouteille de Biere"};
case "life_inv_bottledshine": {"Bouteille de Moonshine"};
case "life_inv_moonshine": {"Moonshine distille"};
case "life_inv_wine": {"Bouteille de Vin"};
case "life_inv_grapes": {"raisin"};
case "life_inv_redburger": {"Menu Giant"};
case "life_inv_frite": {"Frites Rustiques"};
case "life_inv_sprite": {"Canette de Sprite"};
case "life_inv_pepsi": {"Canette de Pepsi"};
case "life_inv_battery": {"Batterie de Téléphone"};
case "life_inv_goldbar": {"Barre d'or"};
case "life_inv_blastingcharge": {"Charge explosive"};
case "life_inv_boltcutter": {"Outils de sérrurier"};
case "life_inv_defusekit": {"kit de désamorçage"};
case "life_inv_storagesmall": {"Petite boîte de rangement"};
case "life_inv_storagebig": {"Grande boîte de rangement"};
case "life_inv_underwatercharge": {"Bombe sous-marine"};
case "life_inv_kidney": {"Rein"};
case "life_inv_zipties": {"Menotte"};
case "life_inv_nitro": {"Kit de Nitro"};
case "life_inv_cafe": {"Café"};
case "life_inv_smoothies": {"Smoothies"};
case "life_inv_speedbomb": {"Bombe de Vitesse"};
case "life_inv_orr": {"Minerai d'or"};
case "life_inv_lingotor": {"Petit lingot d'or"};
case "life_inv_goldbarp": {"Viel Or"};
case "life_inv_scalpel": {"Scalpel"};
case "life_inv_mur": {"Mur"};
case "life_inv_sac": {"Sac de sable"};
case "life_inv_cone": {"Cone Routier"};
case "life_inv_barre": {"Barriere"};
case "life_inv_lightr": {"Lumiere Rouge"};
case "life_inv_lightg": {"Lumiere Verte"};
case "life_inv_lighty": {"Lumiere Jaune"};
case "life_inv_flecheg": {"Fleche Gauche"};
case "life_inv_fleched": {"Fleche Droite"};
case "life_inv_gpstracker": {"Traceur GPS"};
case "life_inv_kit": {"Kit fabrication armes"};
case "life_inv_poudre": {"Poudre a canon"};
case "life_inv_tissu": {"Tissu"};
case "life_inv_electro": {"Kit éléctronique"};
case "life_inv_tobacco": {"Tabac"};
case "life_inv_cigarette": {"Cigarette"};
case "life_inv_cle": {"Clé"};
case "life_inv_cb": {"Carte bleue"};
case "life_inv_marijuanam": {"Medicinal Marijuana"};
case "life_inv_excavator": {"Excavateur d'epaves"};
case "life_inv_doubloon": {"Doublon en Or"};
case "life_inv_silverpiece": {"Piece d'argent"};
case "life_inv_ruby": {"Rubis"};
case "life_inv_diamondf": {"Diamant Pur"};
case "life_inv_pearl": {"Perle"};
case "life_inv_platinep": {"Platine"};
case "life_inv_osmium": {"Osmium"};
case "life_inv_palladium": {"Palladium"};
case "life_inv_camisole": {"Camisole de force"};
case "life_inv_multipass": {"Multipass"};
case "license_civ_special": {"Membre Club V.I.P"};
case "license_civ_rebel": {"Groupe Rebelle"};
case "license_civ_gang": {"Membre d'un Gang"};
case "license_reb_gang1": {"Membre d'une famille"};
case "license_reb_gang2": {"Membre d'une famille"};
case "license_reb_gang3": {"Membre d'une famille"};
case "license_reb_gang4": {"Membre d'une famille"};
case "license_reb_gang5": {"Membre d'une famille"};
case "license_reb_gang6": {"Membre d'une famille"};
case "license_reb_gang7": {"Membre d'une famille"};
case "license_reb_gang8": {"Membre d'une famille"};
case "license_reb_gang9": {"Membre d'une famille"};
case "license_reb_gang10": {"Membre d'une famille"};
case "license_civ_merc": {"Mercenaire"};
case "license_civ_merc_reb": {"Mercenaire Rebelle"};
case "license_civ_usine": {"Enterprise Uranium"};
case "license_civ_bountyh": {"Chasseur de prime"};
case "license_civ_depanneur": {"Dépanneur"};
case "license_civ_taxi": {"Chauffeur de Taxi"};
case "license_civ_gun": {"Permis Port d'armes"};
case "license_civ_driver": {"Permis Voiture"};
case "license_civ_truck": {"Permis Poids-lourd"};
case "license_civ_air": {"Permis Pilote"};
case "license_civ_boat": {"Permis Bateau"};
case "license_civ_dive": {"Permis Plongeur"};
case "license_civ_home": {"Permis Propriétaire"};
case "license_civ_iron": {"Formation Forgeron"};
case "license_civ_skull": {"Formation Archéologie"};
case "license_civ_sand": {"Formation Verrier"};
case "license_civ_bottler": {"Souffleur de verre"};
case "license_civ_salt": {"Formation Salin"};
case "license_civ_cement": {"Formation Ciment"};
case "license_civ_copper": {"Formation Cuivre"};
case "license_civ_oil": {"Formation Pétrole"};
case "license_civ_diamond": {"Formation Diamentaire"};
case "license_civ_lingot": {"Formation Marchand d'Or"};
case "license_civ_grapes": {"Formation Viticulteur"};
case "license_civ_liquor": {"Formation Vendeur d'Alcool"};
case "license_civ_stiller": {"Formation Distillateur"};
case "license_civ_marijuana": {"B.E.P Cannabis"};
case "license_civ_heroin": {"B.T.S Héroïne"};
case "license_civ_coke": {"Doctorat en Cocaïne"};
case "license_civ_meth97": {"Cuisinier de Méth."};
case "license_civ_uranium": {"Formation Uranium"};
case "license_cop_cg": {"Formation Gendarme"};
case "license_cop_driver":{"Permis de Conduire"};
case "license_cop_air": {"Permis de Pilote"};
case "license_cop_swat": {"Membre du GIGN"};
case "license_cop_cea": {"Membre du CEA"};
case "license_med_air": {"Permis de Pilote"};
case "license_civ_mineralogiste": {"Minéralogiste"};
case "license_civ_medmarijuana": {"Marijuana Medicale"};
};